// Auto-generated by Supabase CLI
// Run: supabase gen types typescript --project-id [PROJECT_ID] > lib/supabase/types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          full_name: string | null
          avatar_url: string | null
          is_super_admin: boolean
          created_at: string
        }
        Insert: {
          id: string
          full_name?: string | null
          avatar_url?: string | null
          is_super_admin?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          full_name?: string | null
          avatar_url?: string | null
          is_super_admin?: boolean
          created_at?: string
        }
        Relationships: []
      }
      organizations: {
        Row: {
          id: string
          name: string
          industry: string
          headcount: string
          city: string
          plan_tier: string
          zalo_oa_token: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          industry: string
          headcount: string
          city: string
          plan_tier?: string
          zalo_oa_token?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          industry?: string
          headcount?: string
          city?: string
          plan_tier?: string
          zalo_oa_token?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      users: {
        Row: {
          id: string
          email: string
          full_name: string | null
          zalo_user_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          zalo_user_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          zalo_user_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      org_members: {
        Row: {
          id: string
          org_id: string
          user_id: string
          role: string
          created_at: string
        }
        Insert: {
          id?: string
          org_id: string
          user_id: string
          role: string
          created_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          user_id?: string
          role?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "org_members_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "org_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      x_matrices: {
        Row: {
          id: string
          org_id: string
          year: number
          title: string
          vision_json: Json
          status: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          year?: number
          title: string
          vision_json?: Json
          status?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          year?: number
          title?: string
          vision_json?: Json
          status?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "x_matrices_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      kpis: {
        Row: {
          id: string
          org_id: string
          x_matrix_id: string | null
          owner_user_id: string | null
          name: string
          unit: string
          target_value: number
          frequency: string
          is_active: boolean
          dept_level: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          x_matrix_id?: string | null
          owner_user_id?: string | null
          name: string
          unit: string
          target_value: number
          frequency: string
          is_active?: boolean
          dept_level?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          x_matrix_id?: string | null
          owner_user_id?: string | null
          name?: string
          unit?: string
          target_value?: number
          frequency?: string
          is_active?: boolean
          dept_level?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "kpis_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kpis_x_matrix_id_fkey"
            columns: ["x_matrix_id"]
            isOneToOne: false
            referencedRelation: "x_matrices"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kpis_owner_user_id_fkey"
            columns: ["owner_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      kpi_entries: {
        Row: {
          id: string
          kpi_id: string
          user_id: string
          value: number
          note: string | null
          period_date: string
          created_at: string
        }
        Insert: {
          id?: string
          kpi_id: string
          user_id: string
          value: number
          note?: string | null
          period_date: string
          created_at?: string
        }
        Update: {
          id?: string
          kpi_id?: string
          user_id?: string
          value?: number
          note?: string | null
          period_date?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "kpi_entries_kpi_id_fkey"
            columns: ["kpi_id"]
            isOneToOne: false
            referencedRelation: "kpis"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kpi_entries_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      notification_logs: {
        Row: {
          id: string
          org_id: string
          user_id: string
          type: string
          status: string
          payload: Json
          sent_at: string | null
          opened_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          org_id: string
          user_id: string
          type: string
          status?: string
          payload?: Json
          sent_at?: string | null
          opened_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          user_id?: string
          type?: string
          status?: string
          payload?: Json
          sent_at?: string | null
          opened_at?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "notification_logs_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notification_logs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      swot_analyses: {
        Row: {
          id: string
          org_id: string
          quadrant: string
          framework_source: string
          statement: string
          evidence_json: Json
          implication: string | null
          created_at: string
        }
        Insert: {
          id?: string
          org_id: string
          quadrant: string
          framework_source: string
          statement: string
          evidence_json?: Json
          implication?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          quadrant?: string
          framework_source?: string
          statement?: string
          evidence_json?: Json
          implication?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "swot_analyses_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      discovery_sessions: {
        Row: {
          id: string
          org_id: string
          user_id: string
          step_completed: string | null
          data_json: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          user_id: string
          step_completed?: string | null
          data_json?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          user_id?: string
          step_completed?: string | null
          data_json?: Json
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "discovery_sessions_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "discovery_sessions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      xray_leads: {
        Row: {
          id: string
          email: string
          company_name: string
          industry: string
          headcount: string
          answers_json: Json
          result_json: Json
          overall_score: number
          overall_level: string
          converted: boolean
          created_at: string
        }
        Insert: {
          id?: string
          email: string
          company_name: string
          industry: string
          headcount: string
          answers_json?: Json
          result_json?: Json
          overall_score: number
          overall_level: string
          converted?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          email?: string
          company_name?: string
          industry?: string
          headcount?: string
          answers_json?: Json
          result_json?: Json
          overall_score?: number
          overall_level?: string
          converted?: boolean
          created_at?: string
        }
        Relationships: []
      }
      subscriptions: {
        Row: {
          id: string
          org_id: string
          plan: string
          status: string
          stripe_customer_id: string | null
          current_period_end: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          plan?: string
          status?: string
          stripe_customer_id?: string | null
          current_period_end?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          plan?: string
          status?: string
          stripe_customer_id?: string | null
          current_period_end?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "subscriptions_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: true
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      admin_notes: {
        Row: {
          id: string
          org_id: string
          content: string
          created_at: string
        }
        Insert: {
          id?: string
          org_id: string
          content: string
          created_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          content?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "admin_notes_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      xray_results: {
        Row: {
          id: string
          org_id: string | null
          user_id: string | null
          overall_score: number
          overall_level: string
          result_json: Json
          answers_json: Json
          created_at: string
        }
        Insert: {
          id?: string
          org_id?: string | null
          user_id?: string | null
          overall_score: number
          overall_level: string
          result_json: Json
          answers_json: Json
          created_at?: string
        }
        Update: {
          id?: string
          org_id?: string | null
          user_id?: string | null
          overall_score?: number
          overall_level?: string
          result_json?: Json
          answers_json?: Json
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "xray_results_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "xray_results_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      admin_customers_overview: {
        Row: {
          org_id: string
          org_name: string
          owner_email: string | null
          owner_name: string | null
          plan: string
          sub_status: string
          member_count: number
          created_at: string
          last_active_at: string | null
        }
      }
      admin_customer_detail: {
        Row: {
          org_id: string
          org_name: string
          industry: string
          headcount: string
          city: string
          owner_email: string | null
          owner_name: string | null
          plan: string
          sub_status: string
          current_period_end: string | null
          stripe_customer_id: string | null
          member_count: number
          total_x_matrices: number
          total_sessions: number
          created_at: string
          last_active_at: string | null
        }
      }
    }
    Functions: {
      check_is_super_admin: {
        Args: Record<string, never>
        Returns: boolean
      }
    }
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
